package net.beforetheblight.registry;

import java.util.Objects;
import java.util.function.BiConsumer;

/**
 * Deterministic English translation hook for the door/window slice.
 *
 * <p>This source is generated by tools/export_door_window_assets.py
 * from the same ordered map as en_us.fragment.json.</p>
 */
public final class DoorWindowTranslations {
	private DoorWindowTranslations() {
	}

	public static void addTranslations(BiConsumer<String, String> consumer) {
		Objects.requireNonNull(consumer, "consumer");
		consumer.accept("block.before_the_blight.rough_chestnut_board_door", "Rough Chestnut Board Door");
		consumer.accept("block.before_the_blight.pegged_springhouse_door", "Pegged Springhouse Door");
		consumer.accept("block.before_the_blight.crib_board_hatch", "Crib Board Hatch");
		consumer.accept("block.before_the_blight.cellar_hatch", "Rough Cellar Hatch");
		consumer.accept("block.before_the_blight.small_sash_window", "Small Two-Light Sash Window");
		consumer.accept("block.before_the_blight.two_over_two_sash_window", "Two-over-Two Sash Window");
		consumer.accept("block.before_the_blight.four_over_four_sash_window", "Four-over-Four Sash Window");
		consumer.accept("block.before_the_blight.six_over_six_sash_window", "Six-over-Six Sash Window");
		consumer.accept("block.before_the_blight.fixed_pane_window", "Fixed-Pane Window");
		consumer.accept("block.before_the_blight.operable_sash_window", "Operable Sash Window");
		consumer.accept("block.before_the_blight.broken_pane_sash_window", "Broken-Pane Sash Window");
		consumer.accept("block.before_the_blight.shuttered_sash_window", "Shuttered Sash Window");
		consumer.accept("block.before_the_blight.board_shutter", "Board Shutter");
		consumer.accept("block.before_the_blight.paired_board_shutters", "Paired Board Shutters");
		consumer.accept("block.before_the_blight.rough_chestnut_door_jamb", "Rough Chestnut Door Jamb");
		consumer.accept("block.before_the_blight.hewn_chestnut_lintel", "Hewn Chestnut Lintel");
		consumer.accept("block.before_the_blight.wooden_window_sill", "White Oak Window Sill");
		consumer.accept("block.before_the_blight.rough_door_threshold", "Rough White Oak Threshold");
		consumer.accept("block.before_the_blight.wooden_leveling_wedge", "Wooden Leveling Wedge");
		consumer.accept("block.before_the_blight.installed_wrought_strap_hinge", "Wrought-Iron Strap Hinge");
		consumer.accept("block.before_the_blight.installed_wrought_pintle", "Wrought-Iron Pintle");
		consumer.accept("block.before_the_blight.installed_forged_hasp", "Forged Iron Hasp");
		consumer.accept("block.before_the_blight.installed_forged_staple", "Forged Iron Staple");
		consumer.accept("block.before_the_blight.installed_square_nails", "Hand-Forged Square Nails");
		consumer.accept("block.before_the_blight.installed_cut_nails", "Cut Nails");
		consumer.accept("tag.item.before_the_blight.appalachian_doors", "Appalachian Doors");
		consumer.accept("tag.item.before_the_blight.appalachian_windows", "Appalachian Windows");
		consumer.accept("tag.item.before_the_blight.appalachian_shutters", "Appalachian Shutters");
		consumer.accept("tag.item.before_the_blight.appalachian_hatches", "Appalachian Hatches");
		consumer.accept("tag.item.before_the_blight.opening_trim", "Opening Trim");
		consumer.accept("tag.item.before_the_blight.wall_mounted_props", "Wall-Mounted Props");
		consumer.accept("tag.item.before_the_blight.door_hardware", "Door Hardware");
		consumer.accept("tag.item.before_the_blight.doors_and_windows", "Doors, Windows, and Hardware");
		consumer.accept("rei.before_the_blight.guide.rough_chestnut_board_door", "Craft from six Rough Chestnut Boards.");
		consumer.accept("rei.before_the_blight.guide.pegged_springhouse_door", "Craft from Rough Chestnut Boards and sticks.");
		consumer.accept("rei.before_the_blight.guide.crib_board_hatch", "Craft from six Rough Chestnut Boards.");
		consumer.accept("rei.before_the_blight.guide.cellar_hatch", "Craft from Rough Chestnut Boards and a reinforcing stick.");
		consumer.accept("rei.before_the_blight.guide.small_sash_window", "Craft from Rough Chestnut Boards and glass panes.");
		consumer.accept("rei.before_the_blight.guide.two_over_two_sash_window", "Craft a divided sash from sash-sawn yellow-poplar boards and glass panes.");
		consumer.accept("rei.before_the_blight.guide.four_over_four_sash_window", "Craft a four-over-four sash from sash-sawn yellow-poplar boards and glass panes.");
		consumer.accept("rei.before_the_blight.guide.six_over_six_sash_window", "Craft a prosperous six-over-six sash from sash-sawn yellow-poplar boards and glass panes.");
		consumer.accept("rei.before_the_blight.guide.fixed_pane_window", "Frame one glass pane with sash-sawn yellow-poplar boards.");
		consumer.accept("rei.before_the_blight.guide.operable_sash_window", "What: An operable glazed sash window. Obtain: Craft from sash-sawn yellow-poplar boards, glass panes, and a wooden operating stick. Use: Empty-hand interact to raise or lower the sash; its outline and collision follow the state.");
		consumer.accept("rei.before_the_blight.guide.broken_pane_sash_window", "Craft an unglazed repair frame from sash-sawn yellow-poplar boards.");
		consumer.accept("rei.before_the_blight.guide.shuttered_sash_window", "What: A glazed sash window with synchronized shutters. Obtain: Combine a Two-over-Two Sash Window with two Board Shutters. Use: Empty-hand interact to open or close the shuttered assembly.");
		consumer.accept("rei.before_the_blight.guide.board_shutter", "What: A single operable board shutter. Obtain: Craft two shutters from Rough Chestnut Boards and sticks. Use: Empty-hand interact to swing it open or closed; its outline and collision follow the state.");
		consumer.accept("rei.before_the_blight.guide.paired_board_shutters", "What: A paired operable board-shutter assembly. Obtain: Craft a synchronized pair from Rough Chestnut Boards and sticks. Use: Empty-hand interact to open or close both leaves together.");
		consumer.accept("rei.before_the_blight.guide.rough_chestnut_door_jamb", "Cut three jamb members from Rough Chestnut Boards.");
		consumer.accept("rei.before_the_blight.guide.hewn_chestnut_lintel", "Cut three lintels from Hewn Chestnut Beams.");
		consumer.accept("rei.before_the_blight.guide.wooden_window_sill", "Cut three durable window sills from White Oak Boards.");
		consumer.accept("rei.before_the_blight.guide.rough_door_threshold", "Cut three durable thresholds from White Oak Boards.");
		consumer.accept("rei.before_the_blight.guide.wooden_leveling_wedge", "Cut four leveling wedges from White Oak Boards.");
		consumer.accept("rei.before_the_blight.guide.installed_wrought_strap_hinge", "Forge two strap hinges from iron nuggets.");
		consumer.accept("rei.before_the_blight.guide.installed_wrought_pintle", "Forge two pintles from iron nuggets.");
		consumer.accept("rei.before_the_blight.guide.installed_forged_hasp", "Forge a simple hasp from iron nuggets.");
		consumer.accept("rei.before_the_blight.guide.installed_forged_staple", "Forge two staples from iron nuggets.");
		consumer.accept("rei.before_the_blight.guide.installed_square_nails", "Forge four hand-wrought square-nail clusters from an iron nugget.");
		consumer.accept("rei.before_the_blight.guide.installed_cut_nails", "Cut eight later-period nail clusters from an iron ingot.");
	}
}
