# Optional Continuity CTM rule. Vanilla ignores this resource directory.
method=horizontal
matchBlocks=before_the_blight:rough_spruce_boards
tiles=0-3
connect=block
faces=all
orient=texture
innerSeams=false
